# Generated by Django 5.0.3 on 2024-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("title_name", models.CharField(max_length=30)),
                ("has_passport", models.BooleanField()),
                ("salary", models.IntegerField()),
                ("birth_date", models.DateField()),
                ("hire_date", models.DateField()),
                ("notes", models.CharField(max_length=200)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("IND", "India"),
                            ("BR", "Brazil"),
                            ("UK", "United Kingdom"),
                            ("AUS", "Australia"),
                            ("USA", "United States"),
                            ("AU", "Austria"),
                            ("SP", "SPAIN"),
                        ],
                        default=None,
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
