# Generated by Django 5.0.3 on 2024-05-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PayRollApp", "0002_employee_add_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(default="", max_length=20),
        ),
    ]
