# Generated by Django 5.0.3 on 2024-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PayRollApp", "0003_employee_add_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Country ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Department ID",
                    ),
                ),
                ("dept_name", models.CharField(max_length=30)),
                ("location_name", models.CharField(max_length=30)),
            ],
        ),
    ]
