# Generated by Django 5.0.3 on 2024-06-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PayRollApp", "0004_country_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
