# Generated by Django 5.0.3 on 2024-06-23 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PayRollApp", "0005_alter_country_id_alter_department_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="country",
        ),
        migrations.AddField(
            model_name="employee",
            name="emp_country",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="PayRollApp.country",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emp_department",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="PayRollApp.department",
            ),
        ),
    ]
