# Generated by Django 5.0.3 on 2024-06-23 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PayRollApp", "0006_remove_employee_country_employee_emp_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_country",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Countries",
                to="PayRollApp.country",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_department",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Departments",
                to="PayRollApp.department",
            ),
        ),
    ]
