# Generated by Django 5.0.3 on 2024-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PayRollApp", "0008_alter_employee_emp_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="dept_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="department",
            name="location_name",
            field=models.CharField(max_length=255),
        ),
    ]
