# Generated by Django 5.0.3 on 2024-06-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PayRollApp", "0009_alter_department_dept_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="country_name",
            field=models.CharField(max_length=255),
        ),
    ]
